#!/bin/bash
#----------------------------------------------------------
# Bootstrap an instance of CentOS 7 to be a template for
# building lightweight software development environments.
#
# Run this script as root.
# Assumes fresh install of CentOS 7.
#
# This script installs a few things and sets some
# configuration values to bring the instance up
# to a state that it can run Chef, then it starts
# chef-client to complete the provisioning using
# Chef recipes.
#
# Version 0.1.0
# 24 April 2018
#----------------------------------------------------------

[[ $EUID -ne 0 ]] && 'Please run the bootstrap script as root' && exit 1

yum update -y
yum groupinstall -y 'Development Tools' 

# Chef 2.0.28 requires ruby 2.4
printf "Installing Ruby 2.4.4\n"
curl -sSL https://rvm.io/mpapis.asc | gpg --import -
curl -L get.rvm.io | bash -s stable
usermod -a -G rvm developer 
usermod -a -G rvm root 
source /etc/profile.d/rvm.sh
rvm reload
rvm requirements run 
rvm install 2.4.4
rvm use 2.4.4 --default 
rm -f /usr/local/rvm/rubies/ruby-2.4.4/.irbrc_history

printf "Installing Chef DK.\n"
curl https://omnitruck.chef.io/install.sh | bash -s -- -P chefdk -c stable -v 2.0.28

printf "Copying files from distribution directories to target directories.\n"
cp ./scripts/* /usr/local/bin
mkdir -p /root/chef-repo/cookbooks/centos_prep/spec/unit/recipes
mkdir -p /root/chef-repo/cookbooks/centos_prep/recipes
cp ./centos_prep/Gemfile /root/chef-repo/cookbooks/centos_prep/spec
cp ./centos_prep/Rakefile /root/chef-repo/cookbooks/centos_prep/spec
cp -r ./centos_prep/recipes/* /root/chef-repo/cookbooks/centos_prep/recipes
cp ./centos_prep/spec/spec_helper.rb /root/chef-repo/cookbooks/centos_prep/spec/.
cp -r ./centos_prep/spec/unit/recipes/* /root/chef-repo/cookbooks/centos_prep/spec/unit/recipes

printf "Executing Chef to complete provisioning the instance.\n"
cd /root/chef-repo/cookbooks
chef-client --local-mode --override-runlist centos_prep
